FROM debian:trixie-slim

LABEL name="biointensitynorm"
LABEL version="1.7"

# Copy the uv binary directly from the official Astral image
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

USER root

# Set defaults for build arguments
ARG USER_UID=1000
ARG USER_GID=1000

# Create non-root user and group, and prevent login
RUN groupadd -g $USER_GID eucaim && \
    useradd -r -u $USER_UID -g eucaim -d /home/ds -m -s /usr/sbin/nologin eucaim

ENV DEBIAN_FRONTEND=noninteractive \
    TF_CPP_MIN_LOG_LEVEL=3 \
    KMP_AFFINITY=noverbose \
    GIT_PYTHON_REFRESH=quiet

RUN apt-get update && apt-get install --no-install-recommends -y \
    ffmpeg libsm6 libxext6 \
    git \
    gosu \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


ENV UV_PYTHON_INSTALL_DIR=/opt/uv/python \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    PATH="/app/.venv/bin:$PATH"

RUN git clone --branch eucaim-fem --depth 1 --single-branch https://cbml-gitlab.ics.forth.gr/adovrou/biointensitynorm.git /app && \
    cd /app && \
    uv sync --frozen --no-install-project --no-dev


COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
