[project]
name = "n4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.101",
    "keras-unet-collection>=0.1.13",
    "matplotlib>=3.11.2",
    "nibabel>=5.4.2",
    "numpy<2.0",
    "opencv-python>=4.11.0.86",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "protobuf>=5.29.6",
    "pydicom>=3.0.2",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.1",
    "simpleitk>=2.5.6",
    "tensorflow>=2.18.1",
]
