FROM python:3.12-slim

LABEL name="N4_Bias_Filter"
LABEL version="1.7"

# Copy the uv binary directly from the official Astral image
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

USER root

# Set defaults for build arguments
ARG USER_UID=1000
ARG USER_GID=1000

ARG GIT_REPO_REF=0a1d8ec0e6f8c344c7751c9524c17eded86ad314

# Create non-root user and group, and prevent login
RUN groupadd -g $USER_GID eucaim && \
    useradd -r -u $USER_UID -g eucaim -d /home/ds -m -s /usr/sbin/nologin eucaim

ENV DEBIAN_FRONTEND=noninteractive \
    TF_CPP_MIN_LOG_LEVEL=3 \
    KMP_AFFINITY=noverbose \
    GIT_PYTHON_REFRESH=quiet \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_NO_MANAGED_PYTHON=1 \
    PATH="/home/ds/n4biasfilter/.venv/bin:$PATH"

RUN apt-get update && apt-get install --no-install-recommends -y \
     ffmpeg libsm6 libxext6 git git-lfs \
     gosu build-essential \
    && rm -rf /var/lib/apt/lists/*

# RUN python -m pip install --upgrade pip


RUN git clone --branch eucaim --single-branch https://cbml-gitlab.ics.forth.gr/adovrou/n4biasfilter.git /home/ds/n4biasfilter && \
    cd /home/ds/n4biasfilter && \
    git lfs pull && \
    git -C /home/ds/n4biasfilter checkout ${GIT_REPO_REF}

WORKDIR /home/ds/n4biasfilter

# # sha256:bb6eba7922fa964188aabd2232c115445c4e94e1f41d51ccdc055585662ad8ee
# ADD --checksum=sha256:bb6eba7922fa964188aabd2232c115445c4e94e1f41d51ccdc055585662ad8ee \
#     "https://cbml-gitlab.ics.forth.gr/api/v4/projects/69/repository/files/src%2FBBOX_WEIGHTS%2FWHOLE%20GLAND%2Fcheckpoint_external%2Eh5/raw?ref=${GIT_REPO_REF}&lfs=true" \
#     /app/weights.h5


COPY app/pyproject.toml app/uv.lock* app/.python-version ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

COPY app/main.patch ./ 
RUN git apply main.patch

COPY ./entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh


ENTRYPOINT ["/home/ds/n4biasfilter/entrypoint.sh"]
